const Alldata = [
  {
    img: "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSk_TlFk0-ybHCeJjpmbKwD5m4w2cok1JEVWo_Pjiwy8vBufCtRpY8QEecQpJjpKBvrtUfuBQDI2TC7p7M",
    name: "India Tiger Tour",
    packs: "13 Nights - 14 Days",
    cost: "₹9999",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzxK-yQ8bGG4ZAErKB7_gij_fWKqi_KsA93u53JyZfuKVJOLSow_qUOYEzXpiM2cF2aL8&usqp=CAU",
    name: "Tiger Safari Expedition",
    packs: "9 Nights - 10 Days",
    cost: "₹9999",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy3YlW_IdSToY4SDUzvxOeGggH1gV0QYbF2S7UE-soImPbiPF1VtwurTBc77PPbfpttG4&usqp=CAU",
    name: "North India Birding",
    packs: "13 Nights - 14 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/states/jammu-kashmir/image/best-of-kashmir-it.jpg",
    name: "Best of Kashmir",
    packs: "5 Nights - 6 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/states/himachal/image/beauty-of-himachal-s.webp",
    name: "Himachal Hill Station",
    packs: "9 Nights - 10 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/states/uttarakhand/image/best-of-garhwal2.webp",
    name: "Tawang Hill Station",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/packages-tour-india/pilgrimage-tour-packages/images/chardham-pilgrimage-tour.jpg",
    name: "Chardham Tour",
    packs: "11 Nights - 12 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/packages-tour-india/pilgrimage-tour-packages/images/badirnath-kedarnath-yatra.jpg",
    name: "Badrinath Kedarnath",
    packs: "7 Nights - 8 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/packages-tour-india/pilgrimage-tour-packages/images/hemkund-sahib-yatra.jpg",
    name: "Hemkund Sahib Yatra",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/golden-triangle/golden-images/majestic-tiger/lodi-garden-gallery.webp",
    name: "Golden Triangle Tour",
    packs: "6 Nights - 7 Days",
    cost: "₹9999",
  },
  {
    img: "https://static.toiimg.com/photo/msid-91511440,width-96,height-65.cms",
    name: "Best of Gujarat",
    packs: "9 Nights - 10 Days",
    cost: "₹9999",
  },
  {
    img: "https://s3.india.com/travel/wp-content/uploads/2014/09/Jodhpur1.jpg",
    name: "Forts Tour of Rajasthan",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/uttarakhand01-package.webp",
    name: "Uttarakhand",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/rajasthan-package.webp",
    name: "Rajasthan",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/up-package.webp",
    name: "Uttar Pradesh",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/himachal-package.webp",
    name: "Himachal",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/j&k-package.webp",
    name: "Jammu & Kashmir",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/ladakh-trend.webp",
    name: "Ladakh",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/kerala-package.webp",
    name: "Kerela",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/karnataka-package.webp",
    name: "Karnataka",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/puducherry-package.webp",
    name: "Puducherry",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/tamilnadu-package.webp",
    name: "Tamil Nadu",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/andhra-package.webp",
    name: "Andhra Pradesh",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/telangana-package.webp",
    name: "Telengana",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/sikkim-package.webp",
    name: "Sikkim",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/arunachal-package.webp",
    name: "Arunachal",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/meghalaya-package.webp",
    name: "Meghalaya",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/nagaland-package.webp",
    name: "Nagaland",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/wb-package.webp",
    name: "West Bengal",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/odisha-package.webp",
    name: "Odisha",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/goa-package.webp",
    name: "Goa",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/gujarat-package.webp",
    name: "Gujarat",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/maharashtra-package.webp",
    name: "Maharashtra",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/mp-package.webp",
    name: "Madhya Pradesh",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/ujjain-package.webp",
    name: "Ujjain",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/bhopal-package.webp",
    name: "Bhopal",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/bhutan-package.webp",
    name: " Bhutan",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/thailand-package.webp",
    name: "Thailand",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/srilanaka-package.webp",
    name: "Sri Lanka",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/maldives-package.webp",
    name: "Maldives",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/dubai-package.webp",
    name: "Dubai",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/singapore-package.webp",
    name: "Singapore",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/indonesia-package.webp",
    name: "Indonesia",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/nepal-package.webp",
    name: "Nepal",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/images/cultural-benner61.jpg",
    name: "Andaman Beach Tour",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/images/cultural-benner11.jpg",
    name: "Daman Beach Tour",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/images/cultural-benner41.jpg",
    name: "Lakshadweep Beach",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/packages-tour-india/honeymoon-tour-packages/images/himachal-honeymoon-tour1.jpg",
    name: "Kullu Manali Tour",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/packages-tour-india/honeymoon-tour-packages/images/kashmir-honeymoon-tour2.jpg",
    name: "Kashmir Tour",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/packages-tour-india/honeymoon-tour-packages/images/goa-honeymoon-tour1.jpg",
    name: "Goa Tour",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/treks/wp-content/uploads/2020/08/adi_kailash.jpg",
    name: "Adi Kailash Trek",
    packs: "9 Nights - 10 Days",
  },
  {
    img: "https://www.tourmyindia.com/treks/wp-content/uploads/2020/08/panch_kedar.jpg",
    name: "Kashmir Trek",
    packs: "10 Nights - 11 Days",
  },
  {
    img: "https://www.tourmyindia.com/treks/wp-content/uploads/2020/08/manimahesh-kailash-trek1.jpg",
    name: "Manimahesh Trek",
    packs: "10 Nights - 11 Days",
  },
  {
    img: "https://www.tourmyindia.com/imagess/delhi-tour.webp",
    name: "Weekend Trips From Delhi",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/mumbai-tour.webp",
    name: "Weekend Trips From Mumbai",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/banglore-tour.webp",
    name: "Weekend Trips From Banglore",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/chennai-tour.webp",
    name: "Weekend Trips From Chennai",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/hyderabad-tour.webp",
    name: "Weekend Trips From Hyderabad",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/cochin-tour.webp",
    name: "Weekend Trips From Cochin",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/pune-tour.webp",
    name: "Weekend Trips From Pune",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/nagpur-tour.webp",
    name: "Weekend Trips From Nagpur",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/chandigarh-tour.webp",
    name: "Weekend Trips From Chandigarh",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/jaipur-tour.webp",
    name: "Weekend Trips From Jaipur",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/ahmedabad-tour.webp",
    name: "Weekend Trips From Ahmdabad",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/heritage-tourism.webp",
    name: "Weekend Trips From Agra",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/bhutan1-tours.webp",
    name: "Bhutan Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/thailand1-tours.webp",
    name: "Thailand Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/nepal1-tours.webp",
    name: "Nepal Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/dubai1-tours.webp",
    name: "Dubai Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/malaysia1-tours.webp",
    name: "Malaysia Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/maldives1-tours.webp",
    name: "Maldives Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/indonesia1-tours.webp",
    name: "Indonesia Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/singapore1-tours.webp",
    name: "Singapore Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/vietnam1-tours.webp",
    name: "Vietnam Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/srilanaka-package.webp",
    name: "Hong Kong Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/australia1-tours.webp",
    name: "Australia Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
  {
    img: "https://www.tourmyindia.com/imagess/myanmar1-tours.webp",
    name: "Myanmar Tours",
    packs: "8 Nights - 9 Days",
    cost: "₹9999",
  },
];
export default Alldata;
